/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a band via invite token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcceptInviteResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/{icsToken}.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personal ics feed for one membership */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    icsToken: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token family */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a password reset link */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's bands */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BandSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a band (creator becomes admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBandRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BandDetailResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Band detail + members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BandDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update band settings (admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBandRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/bands/{bandId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active invites */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InviteResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create an invite link (raw token shown once) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["CreateInviteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InviteCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an invite */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    inviteId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone's pattern + exceptions (the week grid) */
        get: {
            parameters: {
                query?: {
                    days?: number | string;
                };
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BandAvailabilityResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/availability/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My pattern, exceptions and calendar feed */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyAvailabilityResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/availability/me/pattern": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace my weekly pattern */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePatternRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyAvailabilityResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/availability/me/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a blockout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExceptionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExceptionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/availability/me/exceptions/{exceptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove my blockout */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exceptionId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/practice-finder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked candidate practice days from patterns + blockouts */
        get: {
            parameters: {
                query?: {
                    days?: number | string;
                    slot?: string;
                };
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeFinderResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming events */
        get: {
            parameters: {
                query?: {
                    days?: number | string;
                };
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventSummaryResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Create a practice/gig/deadline (proposed by default) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEventRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetailResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event detail + rsvps */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/events/{eventId}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set my rsvp (confirms the event at quorum) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RsvpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetailResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/events/{eventId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a proposed event (creator/admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetailResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/events/{eventId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an event (creator/admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetailResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The repertoire */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Add a song */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSongRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/songs/{songId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a song */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    songId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSongRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/bands/{bandId}/song-ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Song ideas with version counts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Start a song idea */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIdeaRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaSummaryResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/song-ideas/{ideaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Idea with versions, stems and polish jobs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ideaId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename/relink/restatus an idea */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ideaId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateIdeaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaSummaryResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/bands/{bandId}/song-ideas/{ideaId}/versions/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a demo upload (presigned url) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ideaId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InitUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InitUploadResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/versions/{versionId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish an upload — verifies the object and its size */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/versions/{versionId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presigned playback url */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamUrlResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a version (uploader/admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/song-ideas/{ideaId}/stems/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a stem upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ideaId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InitStemUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InitStemUploadResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/stems/{stemId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish a stem upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stemId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StemResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/stems/{stemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a stem (uploader/admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stemId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/song-ideas/{ideaId}/polish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mix & master the idea's stems into a new demo version (ai) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ideaId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["RequestPolishRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolishJobResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The band's reference library */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/references/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a reference upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InitReferenceUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InitReferenceUploadResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/references/{referenceId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish a reference upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    referenceId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/references/{referenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a reference (uploader/admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    referenceId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comments on an event or demo version */
        get: {
            parameters: {
                query: {
                    targetType: string;
                    targetId: string;
                };
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Comment (optionally at a timestamp) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCommentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete own comment (or as admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    commentId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Channels (#general always exists) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a channel */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateChannelRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bands/{bandId}/channels/{channelId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages, newest page first */
        get: {
            parameters: {
                query?: {
                    before?: string;
                    take?: number | string;
                };
                header?: never;
                path: {
                    channelId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessagesPage"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Send a message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channelId: string;
                    bandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteResponse: {
            /** Format: uuid */
            bandId: string;
            bandName: string;
            /** Format: uuid */
            membershipId: string;
        };
        BandAvailabilityResponse: {
            from: components["schemas"]["LocalDate"];
            /** Format: int32 */
            days: number | string;
            members: components["schemas"]["MemberAvailabilityResponse"][];
        };
        BandDetailResponse: {
            band: components["schemas"]["BandResponse"];
            members: components["schemas"]["MemberResponse"][];
        };
        /** @enum {unknown} */
        BandPlan: "free" | "pro";
        BandResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            timeZone: string;
            /** Format: int32 */
            quorum: number | string;
            defaultPracticeSlot: components["schemas"]["PracticeSlot"];
            rehearsalSpace: null | string;
            plan: components["schemas"]["BandPlan"];
            /** Format: int64 */
            storageUsedBytes: number;
            /** Format: int64 */
            storageQuotaBytes: number;
        };
        /** @enum {unknown} */
        BandRole: "member" | "admin";
        BandSummaryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            role: components["schemas"]["BandRole"];
        };
        ChannelResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isDefault: boolean;
            createdAt: components["schemas"]["Instant"];
        };
        CommentResponse: {
            /** Format: uuid */
            id: string;
            targetType: components["schemas"]["CommentTarget"];
            /** Format: uuid */
            targetId: string;
            /** Format: uuid */
            authorMembershipId: string;
            authorName: string;
            body: string;
            /** Format: double */
            atSeconds: null | number;
            createdAt: components["schemas"]["Instant"];
        };
        /** @enum {unknown} */
        CommentTarget: "event" | "demoVersion";
        ConfirmUploadRequest: {
            /** Format: double */
            durationSeconds: null | number;
        };
        CreateBandRequest: {
            name: string;
            timeZone: null | string;
        };
        CreateChannelRequest: {
            name: string;
        };
        CreateCommentRequest: {
            targetType: components["schemas"]["CommentTarget"];
            /** Format: uuid */
            targetId: string;
            body: string;
            /** Format: double */
            atSeconds?: null | number;
        };
        CreateEventRequest: {
            type: components["schemas"]["EventType"];
            date: components["schemas"]["LocalDate"];
            slot?: null | components["schemas"]["PracticeSlot"];
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            title?: null | string;
            location?: null | string;
            /** @default false */
            confirmed: boolean;
        };
        CreateExceptionRequest: {
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
            note: null | string;
        };
        CreateIdeaRequest: {
            title: string;
        };
        CreateInviteRequest: {
            /** Format: int32 */
            maxUses: null | number | string;
            /** Format: int32 */
            expiresInDays: null | number | string;
        };
        CreateSongRequest: {
            title: string;
            key?: null | string;
            /** Format: int32 */
            bpm?: null | number | string;
            notes?: null | string;
        };
        EventDetailResponse: {
            event: components["schemas"]["EventSummaryResponse"];
            rsvps: components["schemas"]["RsvpResponse"][];
        };
        /** @enum {unknown} */
        EventStatus: "proposed" | "confirmed" | "cancelled";
        EventSummaryResponse: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["EventType"];
            status: components["schemas"]["EventStatus"];
            date: components["schemas"]["LocalDate"];
            slot: null | components["schemas"]["PracticeSlot"];
            startTime: null | components["schemas"]["LocalTime"];
            endTime: null | components["schemas"]["LocalTime"];
            title: null | string;
            location: null | string;
            /** Format: int32 */
            goingCount: number | string;
        };
        /** @enum {unknown} */
        EventType: "practice" | "gig" | "deadline" | "other";
        ExceptionResponse: {
            /** Format: uuid */
            id: string;
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
            note: null | string;
        };
        FinderCandidateResponse: {
            date: components["schemas"]["LocalDate"];
            slot: components["schemas"]["PracticeSlot"];
            /** Format: int32 */
            availableCount: number | string;
            /** Format: int32 */
            totalMembers: number | string;
            everyoneAvailable: boolean;
            availableMembers: components["schemas"]["FinderMemberDto"][];
        };
        FinderMemberDto: {
            /** Format: uuid */
            membershipId: string;
            displayName: string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        IdeaDetailResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            status: components["schemas"]["IdeaStatus"];
            /** Format: uuid */
            songId: null | string;
            versions: components["schemas"]["VersionResponse"][];
            stems: components["schemas"]["StemResponse"][];
            polishJobs: components["schemas"]["PolishJobResponse"][];
        };
        /** @enum {unknown} */
        IdeaStatus: "idea" | "inProgress" | "finished" | "parked";
        IdeaSummaryResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            status: components["schemas"]["IdeaStatus"];
            /** Format: uuid */
            songId: null | string;
            /** Format: int32 */
            versionCount: number | string;
            latestVersionAt: null | components["schemas"]["Instant"];
            createdAt: components["schemas"]["Instant"];
        };
        InitReferenceUploadRequest: {
            title: string;
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        InitReferenceUploadResponse: {
            /** Format: uuid */
            referenceId: string;
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        InitStemUploadRequest: {
            label: components["schemas"]["StemLabel"];
            name: null | string;
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        InitStemUploadResponse: {
            /** Format: uuid */
            stemId: string;
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        InitUploadRequest: {
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        InitUploadResponse: {
            /** Format: uuid */
            versionId: string;
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** Format: date-time */
        Instant: string;
        InviteCreatedResponse: {
            /** Format: uuid */
            id: string;
            token: string;
            expiresAt: components["schemas"]["Instant"];
            /** Format: int32 */
            maxUses: null | number | string;
        };
        InviteResponse: {
            /** Format: uuid */
            id: string;
            createdAt: components["schemas"]["Instant"];
            expiresAt: components["schemas"]["Instant"];
            /** Format: int32 */
            useCount: number | string;
            /** Format: int32 */
            maxUses: null | number | string;
        };
        /** @enum {unknown} */
        IsoDayOfWeek: "none" | "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
        /** Format: date */
        LocalDate: string;
        /** Format: time */
        LocalTime: string;
        LoginRequest: {
            email: string;
            password: string;
        };
        MemberAvailabilityResponse: {
            /** Format: uuid */
            membershipId: string;
            displayName: string;
            openSlots: components["schemas"]["WeeklySlot"][];
            patternUpdatedAt: null | components["schemas"]["Instant"];
            exceptions: components["schemas"]["ExceptionResponse"][];
        };
        MemberResponse: {
            /** Format: uuid */
            membershipId: string;
            /** Format: uuid */
            userId: string;
            displayName: string;
            role: components["schemas"]["BandRole"];
            instrument: null | string;
            joinedAt: components["schemas"]["Instant"];
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
        };
        MessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            authorMembershipId: string;
            authorName: string;
            body: string;
            createdAt: components["schemas"]["Instant"];
        };
        MessagesPage: {
            items: components["schemas"]["MessageResponse"][];
            nextBefore: null | string;
        };
        MyAvailabilityResponse: {
            openSlots: components["schemas"]["WeeklySlot"][];
            patternUpdatedAt: null | components["schemas"]["Instant"];
            exceptions: components["schemas"]["ExceptionResponse"][];
            calendarFeedPath: string;
        };
        PolishJobResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["PolishStatus"];
            /** Format: uuid */
            outputVersionId: null | string;
            error: null | string;
            createdAt: components["schemas"]["Instant"];
            completedAt: null | components["schemas"]["Instant"];
        };
        /** @enum {unknown} */
        PolishStatus: "queued" | "processing" | "done" | "failed";
        PracticeFinderResponse: {
            from: components["schemas"]["LocalDate"];
            /** Format: int32 */
            days: number | string;
            /** Format: int32 */
            quorum: number | string;
            slot: components["schemas"]["PracticeSlot"];
            candidates: components["schemas"]["FinderCandidateResponse"][];
        };
        /** @enum {unknown} */
        PracticeSlot: "afternoon" | "evening";
        ReferenceResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            fileName: string;
            /** Format: int64 */
            sizeBytes: number;
            status: components["schemas"]["VersionStatus"];
            createdAt: components["schemas"]["Instant"];
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
        };
        RequestPolishRequest: {
            /** Format: uuid */
            referenceTrackId?: null | string;
            /** Format: uuid */
            referenceVersionId?: null | string;
            /** Format: uuid */
            mixReferenceTrackId?: null | string;
            /** Format: uuid */
            mixReferenceVersionId?: null | string;
        };
        ResetPasswordRequest: {
            email: string;
            token: string;
            newPassword: string;
        };
        RsvpRequest: {
            status: components["schemas"]["RsvpStatus"];
            note?: null | string;
        };
        RsvpResponse: {
            /** Format: uuid */
            membershipId: string;
            displayName: string;
            status: components["schemas"]["RsvpStatus"];
            note: null | string;
        };
        /** @enum {unknown} */
        RsvpStatus: "going" | "notGoing" | "maybe";
        SendMessageRequest: {
            body: string;
        };
        SongResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            key: null | string;
            /** Format: int32 */
            bpm: null | number | string;
            status: components["schemas"]["SongStatus"];
            notes: null | string;
            createdAt: components["schemas"]["Instant"];
        };
        /** @enum {unknown} */
        SongStatus: "active" | "retired";
        /** @enum {unknown} */
        StemLabel: "drums" | "bass" | "guitar" | "keys" | "vocals" | "other";
        StemResponse: {
            /** Format: uuid */
            id: string;
            label: components["schemas"]["StemLabel"];
            name: null | string;
            fileName: string;
            /** Format: int64 */
            sizeBytes: number;
            status: components["schemas"]["VersionStatus"];
            createdAt: components["schemas"]["Instant"];
        };
        StreamUrlResponse: {
            url: string;
        };
        TokenPairResponse: {
            accessToken: string;
            /** Format: int32 */
            expiresInSeconds: number | string;
            refreshToken: string;
        };
        UpdateBandRequest: {
            name: null | string;
            timeZone: null | string;
            /** Format: int32 */
            quorum: null | number | string;
            defaultPracticeSlot: null | components["schemas"]["PracticeSlot"];
            rehearsalSpace: null | string;
        };
        UpdateIdeaRequest: {
            title: null | string;
            status: null | components["schemas"]["IdeaStatus"];
            /** Format: uuid */
            songId: null | string;
        };
        UpdatePatternRequest: {
            openSlots: components["schemas"]["WeeklySlot"][];
        };
        UpdateSongRequest: {
            title: null | string;
            key: null | string;
            /** Format: int32 */
            bpm: null | number | string;
            status: null | components["schemas"]["SongStatus"];
            notes: null | string;
        };
        /** @enum {unknown} */
        VersionKind: "upload" | "aiMix";
        VersionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            number: number | string;
            kind: components["schemas"]["VersionKind"];
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: double */
            durationSeconds: null | number;
            uploaderName: string;
            createdAt: components["schemas"]["Instant"];
        };
        /** @enum {unknown} */
        VersionStatus: "uploading" | "ready" | "failed";
        WeeklySlot: {
            day: components["schemas"]["IsoDayOfWeek"];
            slot: components["schemas"]["PracticeSlot"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
